Assignment04
hiro1117/kintone-dojo pull request #4
Opened 2023-06-14 10:41 UTC by hiro1117

レビューよろしくお願いいたします。

2023-06-19 09:25 UTC, H-Shira commented on assignment04/task4-2.html
> +  const HIGHEST_NUM = 5;
LOWEST_NUMとHIGHEST_NUMについては利用してないので、今回は一旦記載は不要かなと思われました

2023-06-19 09:29 UTC, H-Shira commented on assignment04/task4-2.html
> +  };
今回私の画面だと上手く動作しなかったのですが、この「不適切な入力検出処理」部分が悪さをしてるのかなと思われます。
選択肢のvalueが1~5外だった時にfalseをreturnするよう設定してるのかなと解釈したのですが(違かったらごめんなさい🙏)、今回に関してはhtmlで設定されてるslctのvalue以外の値は出ないと思うので削除して良いと思われました。

2023-06-19 09:31 UTC, H-Shira requested changes
お疲れ様です！一次レビューが完了したのでご確認お願いします。
task4-1は内容も動作も問題なかったのでこのままでOKです🙆‍♀️
task4-2が私の画面だと上手く動かなかったので修正お願いします🙏

2023-06-19 09:42 UTC, hiro1117 commented
レビューありがとうございます！
確認したところisValidInputの最後の条件文が悪さをしているようですね。
よく確認してからpull reqをするべきでした。。すみません！
今回は必要ないということでisValidInput()を削除して対応させて頂きます。

2023-06-20 23:29 UTC, merged

2023-06-21 06:07 UTC, H-Shira reviewed
マージ後で恐縮なんですが、私の画面だとtask4-2が動きませんでした> <
`isValidInput`について、修正提案させてもらったので、試してもらえればと思います。
修正などはmainブランチのままで大丈夫です。
終わったらbozumanで通知してもらえるとありがたいです！

2023-06-21 06:07 UTC, H-Shira commented on assignment04/task4-2.html
> +    if (max <= 5 && min >= 1) return false;
※6/21追記
この処理は「`slct`が1~5以外の値を入力された(書き換えられた)時にエラーを出す」目的の処理で間違いないでしょうか？
そうであれば、この「max <= 5 && min >= 1」の場合ではtrueを返すのが良いと思われました！
こちらでtrueを返していれば97行目の処理も正常に動きそうです。